server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      #编码格式
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '@aysz520888'
    #    url: jdbc:mysql://localhost:3306/accreditation?useSSL=false


  redis:
    host: 124.221.16.245
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #接口文档必备
  mvc:
    path match:
      matching-strategy: ant_path_matcher
